spring:
  application:
    name: config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.1.224:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: zcl
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qigemingzidoubujiandan/test
          username: qigemingzidoubujiandan
          password: didiao2013
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: test2222dds
management:
  endpoints:
    web:
      exposure:
        include: "*"
